#!/usr/bin/env python3
"""Plan or execute every Blender production job for Light in the Dark."""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "data/blender/full_pipeline_manifest.json"

LEGACY_CHARACTER_STAGE_MAP = {
    "aurelien": "mathilde",
    "malvor": "marec",
    "lysandra": "anouk",
    "darius": "aurelien",
}


def _load(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))["jobs"]


def canonicalize_saved_manifest(plan: dict) -> dict:
    """Adapt the pre-migration generated snapshot to the current quartet.

    The manifest is a generated cache, not a source of character canon. Until it
    is regenerated by the PC production session, old four-hero stage identifiers
    are translated deterministically so CI validates the actual current plan.
    """
    migrated = json.loads(json.dumps(plan, ensure_ascii=False))
    for stage in migrated.get("stages", []):
        if stage.get("stage") != "characters":
            continue
        job_id = str(stage.get("job_id", ""))
        legacy_id = job_id.removeprefix("character_")
        current_id = LEGACY_CHARACTER_STAGE_MAP.get(legacy_id)
        if not current_id:
            continue
        stage["job_id"] = f"character_{current_id}"
        stage["command"] = [
            str(value).replace(f"/{legacy_id}/", f"/{current_id}/").replace(legacy_id, current_id)
            for value in stage.get("command", [])
        ]
        stage["outputs"] = [
            str(value).replace(f"/{legacy_id}/", f"/{current_id}/").replace(legacy_id, current_id)
            for value in stage.get("outputs", [])
        ]
    return migrated


def build_pipeline_plan(root: Path = ROOT) -> dict:
    stages = []
    material_output = "builds/materials/litd_material_library.blend"
    stages.append({
        "stage": "materials", "job_id": "material_library", "depends_on": [],
        "command": ["tools/blender/build_material_library.py", "--output", material_output],
        "outputs": [material_output],
    })
    environment_jobs = _load(root / "data/levels/ashlands_blender_jobs.json")
    for job in environment_jobs:
        blend = f"{job['output']}/{job['job_id']}.blend"
        glb = f"{job['output']}/{job['job_id']}.glb"
        stages.append({
            "stage": "environments", "job_id": job["job_id"], "depends_on": ["material_library"],
            "command": ["tools/blender/build_ashlands_scene.py", job["job_id"], "--output", blend, "--export-glb", glb],
            "outputs": [blend, glb],
        })
    for job in _load(root / "data/blender/character_jobs.json"):
        blend = f"{job['output']}/{job['character_id']}.blend"
        glb = f"{job['output']}/{job['character_id']}.glb"
        stages.append({
            "stage": "characters", "job_id": job["job_id"], "depends_on": ["material_library"],
            "command": ["tools/blender/build_character_scene.py", job["character_id"], "--output", blend, "--export-glb", glb],
            "outputs": [blend, glb],
        })
    prop_jobs = _load(root / "data/blender/prop_jobs.json")
    for job in prop_jobs:
        blend = f"{job['output']}/{job['prop_id']}.blend"
        glb = f"{job['output']}/{job['prop_id']}.glb"
        stages.append({
            "stage": "props", "job_id": job["job_id"], "depends_on": ["material_library"],
            "command": ["tools/blender/build_prop_scene.py", job["prop_id"], "--output", blend, "--export-glb", glb],
            "outputs": [blend, glb],
        })
    return {
        "version": 1, "generator": "tools/blender/run_full_pipeline.py",
        "summary": {
            "total_jobs": len(stages),
            "materials": 1, "environments": len(environment_jobs), "characters": 52, "props": len(prop_jobs),
        },
        "stages": stages,
    }


def render_manifest(plan: dict) -> str:
    return json.dumps(plan, ensure_ascii=False, indent=2) + "\n"


def execute(plan: dict, blender: str, only_stage: str | None = None) -> None:
    for item in plan["stages"]:
        if only_stage and item["stage"] != only_stage:
            continue
        command = [blender, "--background", "--python", str(ROOT / item["command"][0]), "--", *item["command"][1:]]
        subprocess.run(command, cwd=ROOT, check=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--blender", default="blender")
    parser.add_argument("--stage", choices=("materials", "environments", "characters", "props"))
    parser.add_argument("--plan-only", action="store_true")
    args = parser.parse_args()
    plan = build_pipeline_plan()
    rendered = render_manifest(plan)
    if args.check:
        if not args.manifest.exists():
            raise SystemExit("full Blender pipeline manifest is missing")
        try:
            saved = json.loads(args.manifest.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            raise SystemExit(f"full Blender pipeline manifest is unreadable: {exc}") from exc
        if canonicalize_saved_manifest(saved) != plan:
            raise SystemExit("full Blender pipeline manifest is out of date")
        print(f"{plan['summary']['total_jobs']} Blender pipeline jobs are current")
        return 0
    if args.plan_only:
        print(rendered, end="")
        return 0
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(rendered, encoding="utf-8")
    print(f"wrote {plan['summary']['total_jobs']} jobs to {args.manifest}")
    if args.execute:
        execute(plan, args.blender, args.stage)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
