class_name P0Constants
extends RefCounted

const GRID_WIDTH := 6
const GRID_HEIGHT := 5
const CELL_SIZE := 1.6

const SAHEN_MAX_VIT := 120
const SAHEN_MAX_POSTURE := 65
const RAMPANT_MAX_VIT := 46
const RAMPANT_MAX_POSTURE := 38

const BASIC_ATTACK_VIT := 14
const BASIC_ATTACK_POSTURE := 12

const SHOULDER_BASH_VIT := 12
const SHOULDER_BASH_POSTURE := 22
const SHOULDER_BASH_PUSH := 2

const WALL_COLLISION_VIT_PER_BLOCKED_CELL := 6
const WALL_COLLISION_POSTURE_PER_BLOCKED_CELL := 12
const WALL_COLLISION_TRAUMA_PER_BLOCKED_CELL := 8

const POSTURE_RECOVERY_FRACTION := 0.15
