#!/usr/bin/env python3
"""LITD music production pipeline.

No third-party Python dependencies. REAPER is responsible for orchestration/rendering;
this script validates the production contract, copies finished stems into Godot,
generates the runtime manifest and can ask Godot to import the new audio assets.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import wave

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CONFIG_PATH = HERE / "litd_music_pipeline.json"


def load_config() -> dict:
    with CONFIG_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def resolve_repo_path(value: str) -> Path:
    return (ROOT / value).resolve()


def find_binary(env_name: str, candidates: list[str]) -> str | None:
    explicit = os.environ.get(env_name, "").strip()
    if explicit:
        p = Path(explicit).expanduser()
        if p.exists():
            return str(p)
        found = shutil.which(explicit)
        if found:
            return found
    for candidate in candidates:
        found = shutil.which(candidate)
        if found:
            return found
        p = Path(candidate).expanduser()
        if p.exists():
            return str(p)
    return None


def tools() -> dict[str, str | None]:
    return {
        "musescore": find_binary("MUSESCORE_BIN", [
            "MuseScore4", "mscore", "musescore",
            r"C:\Program Files\MuseScore 4\bin\MuseScore4.exe",
            "/Applications/MuseScore 4.app/Contents/MacOS/mscore",
        ]),
        "reaper": find_binary("REAPER_BIN", [
            "reaper",
            r"C:\Program Files\REAPER (x64)\reaper.exe",
            r"C:\Program Files\REAPER\reaper.exe",
            "/Applications/REAPER.app/Contents/MacOS/REAPER",
        ]),
        "godot": find_binary("GODOT_BIN", [
            "godot", "godot4",
            r"C:\Program Files\Godot\Godot_v4.3-stable_win64.exe",
            "/Applications/Godot.app/Contents/MacOS/Godot",
        ]),
    }


def expected_duration_seconds(cfg: dict) -> float:
    numerator = int(cfg["time_signature"][0])
    bars = int(cfg["bars_per_section"])
    bpm = float(cfg["tempo_bpm"])
    return bars * numerator * 60.0 / bpm


def validate_config(cfg: dict) -> list[str]:
    errors: list[str] = []
    required = [
        "arrangement_id", "tempo_bpm", "time_signature", "bars_per_section",
        "tracks", "sections", "render_root", "godot_asset_root", "godot_manifest",
    ]
    for key in required:
        if key not in cfg:
            errors.append(f"missing config key: {key}")
    if len(cfg.get("tracks", [])) != 10:
        errors.append("LITD production contract requires exactly 10 production tracks")
    if len(set(cfg.get("tracks", []))) != len(cfg.get("tracks", [])):
        errors.append("track names must be unique")
    if len(cfg.get("sections", [])) != 21:
        errors.append("Arrangement 01 requires exactly 21 eight-bar sections")
    if len(set(cfg.get("sections", []))) != len(cfg.get("sections", [])):
        errors.append("section IDs must be unique")
    sig = cfg.get("time_signature", [])
    if sig != [3, 4]:
        errors.append("Arrangement 01 is expected to use 3/4")
    if float(cfg.get("tempo_bpm", 0)) != 52.0:
        errors.append("Arrangement 01 is expected to use 52 BPM")
    return errors


def cmd_doctor(cfg: dict) -> int:
    found = tools()
    print("LITD music pipeline doctor")
    print(f"repo: {ROOT}")
    print(f"config: {CONFIG_PATH}")
    for name, path in found.items():
        print(f"{name:10}: {path or 'NOT FOUND'}")
    source = resolve_repo_path(cfg["source_master_midi"])
    print(f"master MIDI: {source} ({'OK' if source.exists() else 'missing - copy it into inbox'})")
    print(f"8-bar cell: {expected_duration_seconds(cfg):.3f}s")
    return 0 if all(found.values()) else 2


def cmd_prepare(cfg: dict) -> int:
    for rel in [
        cfg["render_root"],
        cfg["godot_asset_root"],
        str(Path(cfg["godot_manifest"]).parent),
        "tools/music_pipeline/inbox",
    ]:
        resolve_repo_path(rel).mkdir(parents=True, exist_ok=True)
    settings = HERE / "reaper" / "litd_generated_settings.lua"
    source = resolve_repo_path(cfg["source_master_midi"]).as_posix()
    render_root = resolve_repo_path(cfg["render_root"]).as_posix()
    lua = (
        "-- Generated by build_music.py; safe to regenerate.\n"
        f'LITD_SOURCE_MIDI = [[{source}]]\n'
        f'LITD_RENDER_ROOT = [[{render_root}]]\n'
        f'LITD_BPM = {float(cfg["tempo_bpm"]):.6f}\n'
        f'LITD_TIME_SIG_NUM = {int(cfg["time_signature"][0])}\n'
        f'LITD_TIME_SIG_DEN = {int(cfg["time_signature"][1])}\n'
        f'LITD_BARS_PER_SECTION = {int(cfg["bars_per_section"])}\n'
    )
    settings.write_text(lua, encoding="utf-8")
    print(f"prepared directories and {settings.relative_to(ROOT)}")
    return 0


def run_checked(args: list[str]) -> None:
    print("+", " ".join(args))
    subprocess.run(args, cwd=ROOT, check=True)


def cmd_musescore_export(cfg: dict, source: str, target: str) -> int:
    binary = tools()["musescore"]
    if not binary:
        print("MuseScore not found. Set MUSESCORE_BIN.", file=sys.stderr)
        return 2
    src = Path(source).expanduser().resolve()
    dst = Path(target).expanduser().resolve()
    dst.parent.mkdir(parents=True, exist_ok=True)
    run_checked([binary, "-o", str(dst), str(src)])
    return 0


def wav_duration(path: Path) -> float | None:
    try:
        with wave.open(str(path), "rb") as wav:
            rate = wav.getframerate()
            if rate <= 0:
                return None
            return wav.getnframes() / float(rate)
    except (wave.Error, EOFError):
        return None


def rendered_file(cfg: dict, section: str, track: str) -> Path:
    return resolve_repo_path(cfg["render_root"]) / f"{section}_{track}.wav"


def cmd_validate_renders(cfg: dict, allow_missing: bool = False) -> int:
    expected = expected_duration_seconds(cfg)
    tolerance = 0.12
    errors: list[str] = []
    missing = 0
    for section in cfg["sections"]:
        for track in cfg["tracks"]:
            path = rendered_file(cfg, section, track)
            if not path.exists():
                missing += 1
                if not allow_missing:
                    errors.append(f"missing: {path.relative_to(ROOT)}")
                continue
            duration = wav_duration(path)
            if duration is None:
                errors.append(f"invalid WAV: {path.relative_to(ROOT)}")
            elif abs(duration - expected) > tolerance:
                errors.append(
                    f"duration mismatch {path.relative_to(ROOT)}: "
                    f"{duration:.3f}s expected {expected:.3f}s"
                )
    print(f"renders checked: {21 * 10 - missing}/210 present")
    if errors:
        for error in errors[:30]:
            print("ERROR:", error, file=sys.stderr)
        if len(errors) > 30:
            print(f"... {len(errors)-30} additional errors", file=sys.stderr)
        return 1
    return 0


def build_manifest(cfg: dict) -> dict:
    root = cfg["godot_asset_root"].rstrip("/")
    sections = {}
    for section in cfg["sections"]:
        stems = {
            track: f"res://{root}/{section}/{track}.wav"
            for track in cfg["tracks"]
        }
        sections[section] = {"bars": cfg["bars_per_section"], "stems": stems}
    return {
        "version": 1,
        "arrangement_id": cfg["arrangement_id"],
        "title": cfg.get("title", cfg["arrangement_id"]),
        "tempo_bpm": cfg["tempo_bpm"],
        "time_signature": cfg["time_signature"],
        "bars_per_section": cfg["bars_per_section"],
        "cell_duration_seconds": expected_duration_seconds(cfg),
        "production_tracks": cfg["tracks"],
        "cue_map": cfg.get("cue_map", {}),
        "runtime_layer_map": cfg.get("runtime_layer_map", {}),
        "sections": sections,
    }


def cmd_sync(cfg: dict) -> int:
    status = cmd_validate_renders(cfg, allow_missing=False)
    if status:
        print("sync aborted: render validation failed", file=sys.stderr)
        return status
    asset_root = resolve_repo_path(cfg["godot_asset_root"])
    for section in cfg["sections"]:
        section_dir = asset_root / section
        section_dir.mkdir(parents=True, exist_ok=True)
        for track in cfg["tracks"]:
            shutil.copy2(rendered_file(cfg, section, track), section_dir / f"{track}.wav")
    manifest_path = resolve_repo_path(cfg["godot_manifest"])
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(build_manifest(cfg), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"synced 210 stems to {asset_root.relative_to(ROOT)}")
    print(f"generated {manifest_path.relative_to(ROOT)}")
    return 0


def cmd_godot_import(cfg: dict) -> int:
    binary = tools()["godot"]
    if not binary:
        print("Godot not found. Set GODOT_BIN.", file=sys.stderr)
        return 2
    run_checked([binary, "--headless", "--path", str(ROOT), "--import"])
    return 0


def cmd_validate_config(cfg: dict) -> int:
    errors = validate_config(cfg)
    if errors:
        for error in errors:
            print("ERROR:", error, file=sys.stderr)
        return 1
    print(
        f"config OK: {len(cfg['tracks'])} tracks x {len(cfg['sections'])} sections "
        f"= {len(cfg['tracks']) * len(cfg['sections'])} stems"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="LITD music production pipeline")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor")
    sub.add_parser("prepare")
    sub.add_parser("validate-config")
    sub.add_parser("validate-renders")
    sub.add_parser("sync")
    sub.add_parser("godot-import")
    export = sub.add_parser("musescore-export")
    export.add_argument("source")
    export.add_argument("target")
    sub.add_parser("finalize", help="validate renders, sync into Godot, then import assets")
    args = parser.parse_args()

    cfg = load_config()
    base_errors = validate_config(cfg)
    if base_errors and args.command != "validate-config":
        for error in base_errors:
            print("ERROR:", error, file=sys.stderr)
        return 1

    if args.command == "doctor":
        return cmd_doctor(cfg)
    if args.command == "prepare":
        return cmd_prepare(cfg)
    if args.command == "validate-config":
        return cmd_validate_config(cfg)
    if args.command == "validate-renders":
        return cmd_validate_renders(cfg)
    if args.command == "sync":
        return cmd_sync(cfg)
    if args.command == "godot-import":
        return cmd_godot_import(cfg)
    if args.command == "musescore-export":
        return cmd_musescore_export(cfg, args.source, args.target)
    if args.command == "finalize":
        if cmd_sync(cfg):
            return 1
        return cmd_godot_import(cfg)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
